checkin:
  fields:
    alt:
      example: 0
      selector:
        text:
    altAcc:
      example: 1
      selector:
        text:
    broadcast:
      example: "public,twitter"
      selector:
        text:
    eventId:
      example: UHR8THISVNT
      selector:
        text:
    ll:
      example: "33.7,44.2"
      selector:
        text:
    llAcc:
      example: 1
      selector:
        text:
    mentions:
      example: "5,10,HZXXY3Y;15,20,GZYYZ3Z;25,30,fbu-GZXY13Y"
      selector:
        text:
    shout:
      example: There are crayons! Crayons!
      selector:
        text:
    venueId:
      required: true
      example: IHR8THISVNU
      selector:
        text:
